[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "atspm"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "pytz",
    "plotly",
    "opencv-python",
    "paramiko",
    "scp"
]

[project.scripts]
atspm = "atspm.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]